"""Add slug to article

Revision ID: 2b395a35360e
Revises: 5187b6ed611a
Create Date: 2015-07-12 13:37:07.163812

"""

# revision identifiers, used by Alembic.
revision = '2b395a35360e'
down_revision = '5187b6ed611a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('slug', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'slug')
    ### end Alembic commands ###
